#!/bin/sh

source swarm_env_vars.env
export \
  SWARM_HOST \
  NUM_WORKERS \
  TIMEOUT \
  REFRESH \
  MAX_FSIZE \
  UNIFIER_INTERNAL_PORT \
  ARCHSTOR_INTERNAL_PORT \
  QREMIS_API_INTERNAL_PORT \
  ACC_IDNEST_INTERNAL_PORT \
  DEAD_SIMPLE_INTERFACE_INTERNAL_PORT \
  REC_API_INTERNAL_PORT \
  UNIFIER_EXTERNAL_PORT \
  ARCHSTOR_EXTERNAL_PORT \
  QREMIS_API_EXTERNAL_PORT \
  ACC_IDNEST_EXTERNAL_PORT \
  DEAD_SIMPLE_INTERFACE_EXTERNAL_PORT \
  REC_API_EXTERNAL_PORT \
  EXTERNAL_ARCHSTOR_URL \
  EXTERNAL_QREMIS_API_URL

envsubst < swarm_stack.template > swarm_stack.yml
